# Architecture identifier.
arch = "riscv64"                    # str
# Platform identifier.
platform = "riscv64-qemu-virt"      # str

#
# Platform configs
#
[plat]
kernel-base = 0x80000000      # uint
mem-size = 0x8000000          # uint

#
# Device specifications
#
[devices]
